---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: filebeat
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubectl
  namespace: kubectl
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: kubectl
      labels:
        app: kubectl
    spec:
      serviceAccount: kubectl
      containers:
      - image: jaganthoutam/kubectl-slackbot:latest
        name: kubectl-slackbot
        env:
        - name: SLACK_API_TOKEN
          value: TOKEN
